### ISSUE TITLE
Access store outside React scope

### ISSUE THREAD

**Issue by DioDread** [catamphetamine/react-isomorphic-render#51]
Hello, I need access Redux store to dispatch action from async callback in utils, which runs separately from react components. How can I obtain app store object.

**Comment by catamphetamine** [comment]
Describe in more detail and paste code

**Comment by DioDread** [comment]
No code, I just rejected all changes... But the situation is following.
I have payment system which is running in iFrame,  and there is async calback, from which I need dispatch some action to application store. There is some hacky way, to export dispatch added to object at runtime, but it's looks very ugly for me. Maybe there is some easy way?

**Comment by catamphetamine** [comment]
From the standpoint of Redux, you'll have to somehow `dispatch()` an action event to the store.
The reference to the Redux store can be obtained using `onStoreCreated(store)` handler
https://github.com/catamphetamine/react-isomorphic-render/blob/master/README-ADVANCED.md
One may store this `store` as `window.store` to later call `window.store.dispatch(action)`

**Comment by DioDread** [comment]
Looks legit! Thank you.
