### ISSUE TITLE
Adding json-ld script tags (dynamic) in SSR pages

### ISSUE THREAD

**Issue by thereviewindex** [catamphetamine/react-isomorphic-render#52]
Hi, I need to add script tags (to indicate JSON-LD structured data) to the Head tag, dynamically for each page, just like title/description/meta tags. What is the recommended way to do this?

Example - 
```
<script type="application/ld+json">
{
  "@context": "http://schema.org",
  "@type": "BreadcrumbList",
  "itemListElement": [{
    "@type": "ListItem",
    "position": 1,
    "item": {
      "@id": "https://example.com/books",
      "name": "Books",
      "image": "http://example.com/images/icon-book.png"
    }
  },{
    "@type": "ListItem",
    "position": 2,
    "item": {
      "@id": "https://example.com/books/authors",
      "name": "Authors",
      "image": "http://example.com/images/icon-author.png"
    }
  }
  }]
}
</script>
```

**Comment by catamphetamine** [comment]
https://stackoverflow.com/a/30956615/970769

> The data, enclosed within the <script type="application/ld+json"> ...  </script> tags as shown in the examples below, may be placed in either the <HEAD> or <BODY> region of the page that displays that event.

Therefore no need to place it in head, place it inside page components.
