### ISSUE TITLE
Can't add custom handler for `@@react-isomorphic-render/goto` event

### ISSUE THREAD

**Issue by shane805** [catamphetamine/react-isomorphic-render#53]
Can't add custom handler for `@@react-isomorphic-render/goto` event.

Is there a different way the event name should be formatted? 

Tried using the `eventName` function to make the string too but no luck.

```
import { action, createHandler, eventName } from 'react-isomorphic-render';

handler.handle('@@react-isomorphic-render/goto', (state, action) => ...
```

**Comment by catamphetamine** [comment]
Why would you need that?

**Comment by shane805** [comment]
I've got something similar to breadcrumbs that I'd like to reset before each `LOCATION_CHANGE`. 

I was able to hook into the `@@router/LOCATION_CHANGE` event but it was resetting any state that was set during the `preload`. 

After looking at this more it looks like `goto` fires after the preload has finished as well. Perhaps using `@@react-isomorphic-render/preload` might be better?

**Comment by catamphetamine** [comment]
Location is only changed after `@preload()` finishes.
Each time location is changed the respective event is emitted:
https://github.com/catamphetamine/react-isomorphic-render/blob/master/source/redux/middleware/history%20middleware.js
https://github.com/catamphetamine/react-isomorphic-render/blob/master/source/redux/actions.js
One can listen for those actions to take actions.
That's supposed to work.

**Comment by shane805** [comment]
Cool, that works. Thanks for the help, much appreciated!
