### ISSUE TITLE
Error running npm install

### ISSUE THREAD

**Issue by justkost** [catamphetamine/react-isomorphic-render#56]
_Node v8.9.0
NPM v5.5.1_

Executing script: build-commonjs-modules
to be executed: babel ./source --out-dir ./build --source-maps 
source/client/CustomEvent.js -> build/client/CustomEvent.js
source/client/cookies.js -> build/client/cookies.js
source/client/history.js -> build/client/history.js
source/client/render.js -> build/client/render.js
source/client/robust-websocket.js -> build/client/robust-websocket.js
source/date parser.js -> build/date parser.js
source/helpers.js -> build/helpers.js
source/history.js -> build/history.js
**SyntaxError: source/http client.js: this is a reserved word (253:9)**
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! react-isomorphic-render@12.0.10 build-commonjs-modules: `better-npm-run build-commonjs-modules`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the react-isomorphic-render@12.0.10 build-commonjs-modules script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

**Comment by catamphetamine** [comment]
What exact command are you running
